apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      volumes:
      - name: sensu-asset-server-ca-cert
        secret:
          secretName: sensu-asset-server-ca-cert
          defaultMode: 256
          optional: true
      containers:
      - name: sensu-agent
        image: sensu/sensu:5.16.1
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        command: ["/opt/sensu/bin/sensu-agent", "start", "--log-level", "debug"]
        env:
          - name: SENSU_BACKEND_URL
            value: ws://10.150.0.8:8081/
          - name: SENSU_NAMESPACE
            value: default
          - name: SENSU_SUBSCRIPTIONS
            value: linux
          - name: SENSU_KEEPALIVE_INTERVAL
            value: "5"
          - name: SENSU_KEEPALIVE_WARNING_TIMEOUT
            value: "10"
          - name: SENSU_KEEPALIVE_CRITICAL_TIMEOUT
            value: "60"
          - name: SENSU_DEREGISTER
            value: "true"
          - name: SENSU_STATSD_EVENT_HANDLERS
            value: statsd
        volumeMounts:
        - name: sensu-asset-server-ca-cert
          mountPath: /etc/pki/ca-trust/source/anchors/sensu-ca-cert.pem # centos
          subPath: sensu-ca-cert.pem
        - name: sensu-asset-server-ca-cert
          mountPath: /usr/local/share/ca-certificates/sensu-ca-cert.crt # alpine/debian
          subPath: sensu-ca-cert
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: GET_HOSTS_FROM
          # value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sensu
spec:
  selector:
    app: sensu
  clusterIP: 	10.150.0.8
  ports:
  - name: sensu-etcd-client
    port: 2379
  - name: sensu-etcd-server
    port: 2380

---
apiVersion: v1
kind: Service
metadata:
  name: sensu-lb
spec:
  selector:
    app: sensu
  type: LoadBalancer
  ports:
  - name: sensu-api
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: sensu-transport
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: sensu-webui
    protocol: TCP
    port: 80
    targetPort: 3000